// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7YhKv01rUeFM-JNR8FT1b5vCOX9-2pZY',
    appId: '1:744830730656:web:e1b169760ad8181e37e4c5',
    messagingSenderId: '744830730656',
    projectId: 'aqlan-spices-shop',
    authDomain: 'aqlan-spices-shop.firebaseapp.com',
    storageBucket: 'aqlan-spices-shop.firebasestorage.app',
    measurementId: 'G-X07HQCHXS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC30oqrTr4YwMwu46yhPM1TnfA4C45IyeA',
    appId: '1:744830730656:android:212c344d922a0e2937e4c5',
    messagingSenderId: '744830730656',
    projectId: 'aqlan-spices-shop',
    storageBucket: 'aqlan-spices-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrTRtlMKbwxbRsQGrIXknWnf3g0U9qlgw',
    appId: '1:744830730656:ios:7db07d7cc2e4914437e4c5',
    messagingSenderId: '744830730656',
    projectId: 'aqlan-spices-shop',
    storageBucket: 'aqlan-spices-shop.firebasestorage.app',
    iosBundleId: 'com.example.aqlanstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7YhKv01rUeFM-JNR8FT1b5vCOX9-2pZY',
    appId: '1:744830730656:web:a657c5ce8454e70137e4c5',
    messagingSenderId: '744830730656',
    projectId: 'aqlan-spices-shop',
    authDomain: 'aqlan-spices-shop.firebaseapp.com',
    storageBucket: 'aqlan-spices-shop.firebasestorage.app',
    measurementId: 'G-Q7LTFHZ6R9',
  );

}