// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIDyuVXQfhzXi82zD7mS1VYoW_4cR4DeE',
    appId: '1:348781799507:web:70f2100ee721a5876efea6',
    messagingSenderId: '348781799507',
    projectId: 'aqlan-spices',
    authDomain: 'aqlan-spices.firebaseapp.com',
    storageBucket: 'aqlan-spices.firebasestorage.app',
    measurementId: 'G-QBTZY0TSR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD97dXbeavWuG-ANmA-YxYjGBcEuVTG9Vg',
    appId: '1:348781799507:android:eeefc31a1893077c6efea6',
    messagingSenderId: '348781799507',
    projectId: 'aqlan-spices',
    storageBucket: 'aqlan-spices.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhicGRpGou0JLj0AWYxbV7olz56VkAQYQ',
    appId: '1:348781799507:ios:d853dd3617e9bbba6efea6',
    messagingSenderId: '348781799507',
    projectId: 'aqlan-spices',
    storageBucket: 'aqlan-spices.firebasestorage.app',
    iosBundleId: 'com.example.aqlanstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIDyuVXQfhzXi82zD7mS1VYoW_4cR4DeE',
    appId: '1:348781799507:web:da7dfb1373e51a166efea6',
    messagingSenderId: '348781799507',
    projectId: 'aqlan-spices',
    authDomain: 'aqlan-spices.firebaseapp.com',
    storageBucket: 'aqlan-spices.firebasestorage.app',
    measurementId: 'G-W9TXZXX22W',
  );

}